using UnityEngine;
using UnityEngine.Rendering;

namespace SmallTown.Core
{
    /// <summary>
    /// All assets the runtime needs, generated by the editor ProjectBuilder and loaded from Resources,
    /// so the game can start from an empty scene. Missing entries are created at runtime as a fallback.
    /// </summary>
    [CreateAssetMenu(menuName = "Small Town/Game Assets", fileName = "SmallTownGameAssets")]
    public sealed class GameAssets : ScriptableObject
    {
        public const string ResourcePath = "SmallTownGameAssets";

        [Header("Materials")]
        [SerializeField] private Material city;
        [SerializeField] private Material grass;
        [SerializeField] private Material foliage;
        [SerializeField] private Material conifer;
        [SerializeField] private Material agents;
        [SerializeField] private Material water;
        [SerializeField] private Material glow;
        [SerializeField] private Material glowAlways;
        [SerializeField] private Material particleAlpha;
        [SerializeField] private Material particleAdditive;

        [Header("Data")]
        [SerializeField] private SimSettingsAsset settings;
        [SerializeField] private TextAsset grammar;
        [SerializeField] private VolumeProfile postProfile;

        public Material City => city;
        public Material Grass => grass;
        public Material Foliage => foliage;
        public Material Conifer => conifer;
        public Material Agents => agents;
        public Material Water => water;
        public Material Glow => glow;
        public Material GlowAlways => glowAlways;
        public Material ParticleAlpha => particleAlpha;
        public Material ParticleAdditive => particleAdditive;
        public SimSettingsAsset Settings => settings;
        public TextAsset Grammar => grammar;
        public VolumeProfile PostProfile => postProfile;

        /// <summary>Runtime fallback when the generated asset is missing: fills every empty slot.</summary>
        public void FillMissing(MaterialSet m)
        {
            if (city == null) city = m.City;
            if (grass == null) grass = m.Grass;
            if (foliage == null) foliage = m.Foliage;
            if (conifer == null) conifer = m.Conifer;
            if (agents == null) agents = m.Agents;
            if (water == null) water = m.Water;
            if (glow == null) glow = m.Glow;
            if (glowAlways == null) glowAlways = m.GlowAlways;
            if (particleAlpha == null) particleAlpha = m.ParticleAlpha;
            if (particleAdditive == null) particleAdditive = m.ParticleAdditive;
        }

        public void SetGrammar(TextAsset text)
        {
            if (grammar == null) grammar = text;
        }
    }

    /// <summary>Materials created from shaders at runtime (used when generated assets are absent).</summary>
    public sealed class MaterialSet
    {
        public Material City, Grass, Foliage, Conifer, Agents, Water, Glow, GlowAlways, ParticleAlpha, ParticleAdditive;

        public static MaterialSet Create()
        {
            var s = new MaterialSet();
            var toy = Shader.Find("SmallTown/ToyLit");
            var toyAgents = Shader.Find("SmallTown/ToyLitAgents");
            var water = Shader.Find("SmallTown/Water");
            var glow = Shader.Find("SmallTown/Glow");
            var particle = Shader.Find("SmallTown/Particle");
            s.City = Configure(new Material(toy) { name = "M_City" }, Color.white, 0.12f, 1f);
            s.Grass = Configure(new Material(toy) { name = "M_Grass" }, new Color(0.52f, 0.74f, 0.42f), 0.05f, 1f);
            s.Foliage = Configure(new Material(toy) { name = "M_Foliage" }, new Color(0.40f, 0.66f, 0.34f), 0.05f, 1f);
            s.Conifer = Configure(new Material(toy) { name = "M_Conifer" }, new Color(0.26f, 0.48f, 0.34f), 0.05f, 1f);
            s.Agents = Configure(new Material(toyAgents) { name = "M_Agents", enableInstancing = true }, Color.white, 0.3f, 0.6f);
            s.Water = new Material(water) { name = "M_Water", renderQueue = 2990 };
            s.Glow = new Material(glow) { name = "M_Glow", enableInstancing = true };
            s.Glow.SetFloat("_NightOnly", 1f);
            s.GlowAlways = new Material(glow) { name = "M_GlowAlways", enableInstancing = true };
            s.GlowAlways.SetFloat("_NightOnly", 0f);
            s.GlowAlways.SetFloat("_Intensity", 2.2f);
            s.GlowAlways.SetColor("_Color", Color.white);
            s.ParticleAlpha = new Material(particle) { name = "M_ParticleAlpha" };
            s.ParticleAlpha.SetFloat("_SrcBlend", (float)BlendMode.SrcAlpha);
            s.ParticleAlpha.SetFloat("_DstBlend", (float)BlendMode.OneMinusSrcAlpha);
            s.ParticleAdditive = new Material(particle) { name = "M_ParticleAdditive" };
            s.ParticleAdditive.SetFloat("_SrcBlend", (float)BlendMode.SrcAlpha);
            s.ParticleAdditive.SetFloat("_DstBlend", (float)BlendMode.One);
            return s;
        }

        public static Material Configure(Material m, Color tint, float smoothness, float snow)
        {
            m.SetColor("_BaseColor", tint);
            m.SetFloat("_Smoothness", smoothness);
            m.SetFloat("_SnowBlend", snow);
            m.SetFloat("_EmissionBoost", 1f);
            m.enableInstancing = true;
            return m;
        }
    }
}
